#!/usr/bin/env python3
"""
Tobbes v2 - Spårbarhetsguiden
Main entry point for the application
"""

import sys
from pathlib import Path

# Add project root to Python path
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))


def main():
    """Main application entry point."""
    print("=" * 60)
    print("Tobbes v2 - Spårbarhetsguiden")
    print("Version: 2.0.0")
    print("=" * 60)
    print()
    print("🚧 Under utveckling...")
    print()
    print("✅ Dag 1-2 Setup KLAR:")
    print("  ✅ Projektstruktur skapad")
    print("  ✅ Dependencies installerade")
    print("  ✅ DatabaseInterface ABC (488 rader, 30+ metoder)")
    print("  ✅ 4 migrations skapade")
    print()
    print("✅ Dag 3-4 Database Layer KLAR:")
    print("  ✅ SQLiteDatabase implementation (438 rader)")
    print("  ✅ SQL queries modul (186 rader)")
    print("  ✅ Database factory (create_database)")
    print("  ✅ Custom exceptions (DatabaseError, etc.)")
    print("  ✅ 10/10 unit tests passerar")
    print()
    print("✅ Dag 5-7 Domain Layer KLAR:")
    print("  ✅ Domain models (9 dataclasses)")
    print("  ✅ Validators (10 functions)")
    print("  ✅ Business rules (9 functions)")
    print("  ✅ 10 unit tests (20 totalt)")
    print()
    print("✅ Services Layer KOMPLETT (Dag 5-6):")
    print("  ✅ Chrome Checker + Excel Reader (26 tests)")
    print("  ✅ File Service - Filhantering (NY!)")
    print("  ✅ PDF Service - PDF-generering med Playwright (NY!)")
    print()
    print("✅ Operations Layer KOMPLETT (Dag 6-10):")
    print("  ✅ import_ops.py - Import Excel-filer (17 tests)")
    print("  ✅ process_ops.py - Matchningslogik KRITISK (11 tests)")
    print("  ✅ certificate_ops.py - Certifikathantering (15 tests)")
    print("  ✅ article_ops.py - Global notes NY! (13 tests)")
    print("     - update_article_notes() - Delad över projekt")
    print("     - get_articles_for_project() - Med global data")
    print("     - get_notes_history() - Audit log")
    print("  ✅ update_ops.py - Projekt-uppdatering NY! (15 tests)")
    print("     - compare_articles_for_update() - Jämför data")
    print("     - apply_updates() - Applicera med cert-borttagning")
    print("     - get_update_summary() - Statistik")
    print("  ✅ 117/117 totala unit tests passerar (100%)")
    print()
    print("✅ Config Layer KOMPLETT (Dag 11):")
    print("  ✅ constants.py - Alla applikationskonstanter")
    print("  ✅ settings.py - Settings med from_env()")
    print("  ✅ app_context.py - AppContext för dependency injection (NY!)")
    print()
    print("✅ UI Layer - CORE PAGES KLARA (Dag 11-15):")
    print("  ✅ styles.py - Qt stylesheet + HTML CSS")
    print("  ✅ wizard.py - Main QWizard med AppContext (NY!)")
    print("  ✅ pages/start_page.py - Projekt CRUD (NY!)")
    print("  ✅ pages/import_page.py - Import nivålista + lagerlogg (NY!)")
    print("  ✅ pages/process_page.py - Matchning med färgkodning (NY!)")
    print("  ✅ pages/export_page.py - Artikel-lista + placeholders (NY!)")
    print()
    print("Komplett Workflow Implementerad:")
    print("  1. Välj/skapa projekt ✅")
    print("  2. Importera Excel-filer ✅")
    print("  3. Matcha artiklar med charger ✅")
    print("  4. Granska och exportera ✅")
    print()
    print("✅ Week 4 - Widgets & Report KOMPLETT (Dag 16-20):")
    print("  ✅ ui/widgets/article_card.py - Global notes med auto-save")
    print("  ✅ ui/dialogs/certificate_upload_dialog.py - Upload med auto-detect")
    print("  ✅ operations/report_ops.py - PDF-generering med watermark")
    print("  ✅ Export page - Certifikat upload + PDF rapport")
    print()
    print("✅ Week 5 - TESTING KOMPLETT (Dag 21-25):")
    print("  ✅ Unit tests: 166 passerar (report_ops + file_service)")
    print("  ✅ Integration tests: 6 passerar (complete workflow)")
    print("  ✅ Test coverage: 83% (mål: 80%+)")
    print("  ✅ TOTALT: 172/172 tester passerar (100%)")
    print()
    print("✅ Week 5-6 - V1 UI RECREATION KOMPLETT (Dag 26-28):")
    print("  ✅ Migration 005 - Extended project metadata")
    print("     - purchase_order_number (Beställningsnummer)")
    print("     - project_type (Doc/Ej Doc)")
    print("  ✅ DatabaseInterface.get_project_statistics() - Verification counts")
    print("  ✅ StartPage TOTAL OMSKRIVNING:")
    print("     - Inline project creation (inte dialog)")
    print("     - 7-kolumns tabell: Beställningsnr, Ordernr, Artikelbenämning,")
    print("       Typ, Kund, Verifierade (X/Y), Senast ändrad")
    print("     - Welcome section med HTML bullets")
    print("     - 4 action buttons: Update, Edit cert types, Sort A-Z, Open folder")
    print("     - Red border validation feedback")
    print("     - Enter key support + auto-clear")
    print("  ✅ Cross-platform project folder opening")
    print("  ✅ Real-time verification statistics från databas")
    print()
    print("⏳ Nästa (Week 6 - Remaining Features):")
    print("  ⏳ UpdatePage - Import nya versioner av nivålistor")
    print("  ⏳ CertificateTypesDialog - Hantera globala certifikattyper")
    print("  ⏳ Nuitka build pipeline setup")
    print("  ⏳ .exe compilation och test")
    print("  ⏳ Final release build")
    print()
    print("=" * 60)

    # Launch GUI wizard
    try:
        from PySide6.QtWidgets import QApplication
        from ui.wizard import TobbesWizard

        app = QApplication(sys.argv)
        wizard = TobbesWizard()
        wizard.show()
        sys.exit(app.exec())
    except Exception as e:
        print(f"\n❌ Failed to launch GUI: {e}")
        print("Run in development mode: python -m pytest tests/")
        sys.exit(1)


if __name__ == "__main__":
    main()
