name: Build Windows EXE (Nuitka)

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -U pip wheel
          pip install -r requirements.txt
          pip install -r requirements-build.txt

      - name: Build EXE with Nuitka
        run: |
          python -m nuitka ^
            --standalone ^
            --output-dir=dist ^
            --enable-plugin=pyside6 ^
            --include-package=operations ^
            --include-package=domain ^
            --include-package=data ^
            --include-package=services ^
            --include-package=config ^
            --include-package=ui ^
            --include-data-dir=data/migrations=data/migrations ^
            --jobs=4 ^
            --lto=yes ^
            --python-flag=no_site ^
            --python-flag=no_warnings ^
            --follow-imports ^
            --assume-yes-for-downloads ^
            --windows-disable-console ^
            --windows-company-name=FA-TEC ^
            --windows-product-name="Tobbes v2 - Spårbarhetsguiden" ^
            --windows-file-version=2.0.0 ^
            --windows-product-version=2.0.0 ^
            --windows-file-description="Spårbarhetsguide för materialcertifikat" ^
            main.py

      - name: Create release package
        run: |
          cd dist
          Compress-Archive -Path main.dist -DestinationPath TobbesWizard-v2.0.0-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TobbesWizard-Windows
          path: |
            dist/main.dist/**
            dist/TobbesWizard-v2.0.0-windows.zip
          retention-days: 30

      - name: Create release (on tags)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/TobbesWizard-v2.0.0-windows.zip
          draft: false
          prerelease: false
